LOGINPUA/Controllers/PicoPlacaController.cs
using ENTIDADES;
using LN.EntidadesLN;
using LOGINPUA.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpreadsheetLight;
using Newtonsoft.Json;
using System.Globalization;
using System.Transactions;
using System.IO.Compression;
using LN.Reportes;

namespace LOGINPUA.Controllers
{
    public class PicoPlacaController : Controller
    {
        //Reporte_ComparativoV model_rp = new Reporte_ComparativoV();

        //private readonly CorredoresLN _CorredoresLN;
        //private readonly RutaLN _rutaLN;
        //private readonly RegistroPicoPlacaLN _registroPicoPlacaLN;
        //Util.Util utilidades = new Util.Util();

        //public PicoPlacaController()
        //{
        //    _CorredoresLN = new CorredoresLN();
        //    _rutaLN = new RutaLN();
        //    _registroPicoPlacaLN = new RegistroPicoPlacaLN();

        //}
        // GET: PicoPlaca
        public ActionResult RegistroPicoPlaca()
        {
            Util.Util utilidades = new Util.Util();
            CorredoresLN _CorredoresLN = new CorredoresLN();
            RutaLN _rutaLN = new RutaLN();

            String mensaje = "";
            Int32 tipo = 0;
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);
            var Lista_acciones = utilidades.validadAccionMenu(listacciones, nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();
            if (auxValida)
            {
                var datosCorredores = _CorredoresLN.obtenerListaCorredores(ref mensaje, ref tipo);
                ViewBag.Accionesview = Lista_acciones; 
                ViewBag.rutas = _rutaLN.getRutaCorredor(ref mensaje, ref tipo);
                ViewBag.corredores = JsonConvert.SerializeObject(datosCorredores);

                return View(_CorredoresLN.obtenerListaCorredores(ref mensaje, ref tipo));
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }
        }
        public ActionResult Reporte()
        {
            Util.Util utilidades = new Util.Util();
             RutaLN _rutaLN = new RutaLN();

            String mensaje = "";
            Int32 tipo = 0;
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);
            var Lista_acciones = utilidades.validadAccionMenu(listacciones,nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();
            if (auxValida)
            {
                ViewBag.Accionesview = Lista_acciones;
                var rutas = _rutaLN.getRutaCorredor(ref mensaje, ref tipo);
                return View(rutas);
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }
        }

        public string ConsultarHoras(string fechaInicio, string fechaFin, int id_ruta)
        {
            RegistroPicoPlacaLN _registroPicoPlacaLN = new RegistroPicoPlacaLN();
            String mensaje = "";
            Int32 tipo = 0;

            string fechaInicio_cambiada = fechaInicio.Replace(" ", "");
            fechaInicio_cambiada = fechaInicio_cambiada.Replace("-", "|");
            string fechaFin_cambiada = fechaFin.Replace(" ", "");
            fechaFin_cambiada = fechaFin_cambiada.Replace("-", "|");


            var Tabla1 = _registroPicoPlacaLN.getHora_Comparativo(fechaInicio_cambiada, id_ruta, "MAÑANA", ref mensaje, ref tipo);
            var Tabla2 = _registroPicoPlacaLN.getHora_Comparativo(fechaInicio_cambiada, id_ruta, "TARDE", ref mensaje, ref tipo);

            var Tabla3 = _registroPicoPlacaLN.getHora_Comparativo(fechaFin_cambiada, id_ruta, "MAÑANA", ref mensaje, ref tipo);
            var Tabla4 = _registroPicoPlacaLN.getHora_Comparativo(fechaFin_cambiada, id_ruta, "TARDE", ref mensaje, ref tipo);


            List<CC_HORAS> horas_1 = new List<CC_HORAS>();
            List<CC_HORAS> horas_2 = new List<CC_HORAS>();
            List<CC_HORAS> horas_3 = new List<CC_HORAS>();
            List<CC_HORAS> horas_4 = new List<CC_HORAS>();


            //RECORRER mañanaida
            foreach (var item in Tabla1)
            {
                CC_HORAS horas = new CC_HORAS();

                horas.mañanaida = item.TIEMPO_IDA;
                horas.mañanavuelta = item.TIEMPO_VUELTA;
                horas_1.Add(horas);
            }
            //RECORRER mañanaida

            foreach (var item in Tabla2)
            {
                CC_HORAS horas = new CC_HORAS();

                horas.mañanaida = item.TIEMPO_IDA;
                horas.mañanavuelta = item.TIEMPO_VUELTA;
                horas_2.Add(horas);
            }
            //RECORRER mañanaida

            foreach (var item in Tabla3)
            {
                CC_HORAS horas = new CC_HORAS();

                horas.mañanaida = item.TIEMPO_IDA;
                horas.mañanavuelta = item.TIEMPO_VUELTA;
                horas_3.Add(horas);
            }
            //RECORRER mañanaida

            foreach (var item in Tabla4)
            {
                CC_HORAS horas = new CC_HORAS();

                horas.mañanaida = item.TIEMPO_IDA;
                horas.mañanavuelta = item.TIEMPO_VUELTA;
                horas_4.Add(horas);
            }


            var data_ = new Dictionary<string, List<CC_HORAS>>(); //columna, nombre

            data_.Add("d_manana_ida", horas_1);
            data_.Add("d_manana_vuelta", horas_2);
            data_.Add("d_tarde_ida", horas_3);
            data_.Add("d_tarde_vuelta", horas_4);

            //            var result = JsonConvert.SerializeObject(); //para la lista principal 
            var result = JsonConvert.SerializeObject(data_); //para la lista principal
            return result;
        }
        public string Reporte_Comparativo(string fechaInicio, string fechaFin, int id_ruta, string MAÑANA_IDA, string MAÑANA_VUELTA, string TARDE_IDA, string TARDE_VUELTA)
        {
            RegistroPicoPlacaLN _registroPicoPlacaLN = new RegistroPicoPlacaLN();
            Reporte_ComparativoV model_rp = new Reporte_ComparativoV();
            RutaLN _rutaLN = new RutaLN();

            String mensaje = "";
            Int32 tipo = 0;
            CC_REPORTE_PICO_PLACA model = new CC_REPORTE_PICO_PLACA();


            string fechaInicio_cambiada = fechaInicio.Replace(" ", "");
            fechaInicio_cambiada = fechaInicio_cambiada.Replace("-", "|");
            string fechaFin_cambiada = fechaFin.Replace(" ", "");
            fechaFin_cambiada = fechaFin_cambiada.Replace("-", "|");
            //CONSULTA MAÑANA
            var Tabla1 = _registroPicoPlacaLN.getReporte_Comparativo(fechaInicio_cambiada, id_ruta, "MAÑANA", MAÑANA_IDA, MAÑANA_VUELTA, ref mensaje, ref tipo);
            var Tabla2 = _registroPicoPlacaLN.getReporte_Comparativo(fechaFin_cambiada, id_ruta, "MAÑANA", MAÑANA_IDA, MAÑANA_VUELTA, ref mensaje, ref tipo);

            //CONSULTA TARDE
            var Tabla3 = _registroPicoPlacaLN.getReporte_Comparativo(fechaInicio_cambiada, id_ruta, "TARDE", TARDE_IDA, TARDE_VUELTA, ref mensaje, ref tipo);
            var Tabla4 = _registroPicoPlacaLN.getReporte_Comparativo(fechaFin_cambiada, id_ruta, "TARDE", TARDE_IDA, TARDE_VUELTA, ref mensaje, ref tipo);



            if (Tabla1.Count > 0 && Tabla2.Count > 0 && Tabla3.Count > 0 && Tabla4.Count > 0)
            {
                //TABLA 1
                foreach (var item in Tabla1)
                {
                    //VELOCIDAD TIEMPO A Y B
                    model_rp.suma_tiempo_A = Double.Parse(item.TIEMPO_PROM_A);
                    model_rp.suma_tiempo_B = Double.Parse(item.TIEMPO_PROM_B);
                    if (model_rp.suma_tiempo_A > 0)
                    {
                        model_rp.contador_tiempoa++;
                        model_rp.total_tiempo_a += model_rp.suma_tiempo_A;
                    }
                    if (model_rp.suma_tiempo_B > 0)
                    {
                        model_rp.contador_tiempob++;
                        model_rp.total_tiempo_b += model_rp.suma_tiempo_B;
                    }
                    //VELOCIDAD PROMEDIO
                    model_rp.suma_velocidad_A = item.VEL_PROMEDIO_AB;
                    model_rp.suma_velocidad_B = item.VEL_PROMEDIO_BA;

                    if (model_rp.suma_velocidad_A > 0)
                    {
                        model_rp.TOTAL_a_velocidad += model_rp.suma_velocidad_A;
                        model_rp.contador_velocidad_a++;
                    }

                    if (model_rp.suma_velocidad_B > 0)
                    {
                        model_rp.TOTAL_b_velocidad += model_rp.suma_velocidad_B;
                        model_rp.contador_velocidad_b++;

                    }
                }
                //PROMEDIO

LOGINPUA/Views/PicoPlaca/RegistroPicoPlaca.cshtml
@model IEnumerable<ENTIDADES.CC_CORREDOR>
@{
    ViewBag.Title = "RegistroPicoPlaca";
    //Layout = "~/Views/Shared/_Layout_corredores_Supervisor.cshtml";
    Layout = "~/Views/Shared/_LayoutInicial.cshtml";

    List<ENTIDADES.CC_MENUPERFIL_ACCION> Lista_acciones = ViewBag.Accionesview as List<ENTIDADES.CC_MENUPERFIL_ACCION>;
    int ideliminar = 0;
    int idmodificar = 0;
}
<style>
    .modal-dialog {
        max-width: max-content !important;
    }

    .modal-content input {
        width: 413px;
    }

    .sombraContenedor {
        background-color: white;
        box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
    }

    .modal-content input {
        width: auto !important;
    }

    .row{
        margin-left: 0px !important;
        margin-right: 0px !important;
    }
</style>

@*<link href="~/Content/plugins/datepicker/bootstrap-datepicker3.min.css" rel="stylesheet" />
<link href="~/Content/plugins/sweetAlert/sweetalert2.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
<link href="~/Content/plugins/datepicker/bootstrap-datepicker3.min.css" rel="stylesheet" />*@ 

<script src="~/Content/js/js_registro_pico_placa/js_registroPicoPlaca.js"></script>
@*<script src="~/Content/plugins/sweetAlert/sweetalert2.js"></script>
<script src="~/Content/plugins/datepicker/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.4/xlsx.core.min.js"></script>
<script src="~/Scripts/exportar_excel/FileSaver.js"></script>
<script src="~/Scripts/exportar_excel/jhxlsx.js"></script>
<script src="~/Content/plugins/datepicker/bootstrap-datepicker.min.js"></script>
<script src="~/Content/plugins/moment/moment.js"></script>
<script src="~/Scripts/Utilidades/Util.js"></script>*@

@{
    List<ENTIDADES.CC_RUTA_CORREDOR> listRutas = new List<ENTIDADES.CC_RUTA_CORREDOR>();
    listRutas = ViewBag.rutas;
}
<br />

<div class="row">
    <div class="col-md-12 text-center">
        <h4>Registro Pico Placa&nbsp;&nbsp;&nbsp;

            @foreach (var item in Lista_acciones)
            {
                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.REGISTRAR.ToString()) //cambiar a enumerado
                {
                    <button type="button" id="btnRegistrarPicoPlaca" class="btn btn-success btn-sm" data-toggle="modal" onclick="AbrirModalRegistroPicoPlaca();">
                        <span class="fa fa-plus"></span>
                    </button>
                }

                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.MODIFICAR.ToString())
                {
                    idmodificar = 1;
                    <input type="text" id="permisoActualiza" value="1" hidden />
                }
                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.ANULAR.ToString())
                {
                    ideliminar = 1;
                    <input type="text" id="permisoEliminar" value="1" hidden />
                }
            }


        </h4>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-2">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" title="Ruta"><span class="fas fa-road" aria-hidden="true"></span></span>
            </div>

            <select class="form-control form-control-sm" id="selectRutaCorredor">
                @foreach (var item in listRutas)
                {
                <option value="@item.ID_RUTA">@item.ABREV_CORREDOR   @item.NRO_RUTA</option>
                }
            </select>

        </div>
    </div>

    <div class="col-md-2">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><span class="fa fa-calendar"></span></span>
            </div>
            <input type="text" id="txtFechaConsultaIni" value="01/08/2019" class="form-control form-control-sm" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <select class="form-control form-control-sm" id="selectCorredores" hidden>
            @foreach (var item in Model)
            {
                <option value="@item.ID_CORREDOR">@item.ABREVIATURA</option>
            }
        </select>
    </div>
    <div class="col-md-2">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><span class="fa fa-calendar"></span></span>
            </div>
            <input type="text" id="txtFechaConsultaFin" value="@DateTime.Now.ToString("dd/MM/yyyy")" class="form-control form-control-sm" aria-label="Username" aria-describedby="basic-addon1">
        </div>
    </div>
    <div class="col-md-1" style="display: contents;" >
        <a href="#" id="consultar" class="btn btn-info btn-sm" data-toggle="modal" onclick="consultarData();">Consultar</a>
    </div>
    <div class="col-md-4 text-right">
        <a href="" id="exportar" class="btn btn-success btn-sm" data-toggle="modal" onclick="exportarTabla();">Exportar</a>
    </div>
    @*<div class="col-md-2">
        <a href="" id="btnRegistrarPicoPlaca" class="btn btn-info btn-sm" data-toggle="modal" onclick="AbrirModalRegistroPicoPlaca();" >Registrar</a>
    </div>
    <div class="col-md-4">

    </div>*@
</div>
<hr />
<div class="row">
    <div class="table-responsive">
        <table class="responsive-table" id="tbReportePicoPlaca" style="width:100%">
            <thead >
                <tr>
                    <th rowspan="2" style="vertical-align:middle;">FECHA</th>
                    <th rowspan="2" style="vertical-align:middle;">CORREDOR</th>
                    <th rowspan="2" class="text-center" style="vertical-align:middle;">RUTA</th>
                    <th colspan="2" class="text-center">HORA</th>
                    <th colspan="2" class="text-center">DISTANCIA</th>
                    <th colspan="2" class="text-center">VELOCIDAD PROM</th>
                    <th colspan="2" class="text-center">TIEMPO PROM</th>
                    <th rowspan="2" style="vertical-align:middle;" class="text-right">USUARIO REG</th>
                    <th rowspan="2" style="vertical-align:middle;" class="text-right">FECHA REG</th>
                </tr>

                <tr>
                    <th class="text-center">INI</th>
                    <th class="text-center">FIN</th>
                    <th class="text-center">AB</th>
                    <th class="text-center">BA</th>
                    <th class="text-center">AB</th>
                    <th class="text-center">BA</th>
                    <th class="text-center">AB</th>
                    <th class="text-center">BA</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="13" class="text-center">Presionar el boton Consultar para obtener la información.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@Html.Partial("_RegistroPicoPlaca")

<script>
    var Utilidades = new Util();
    var URL_GET_RUTA_X_CORREDOR = "@Url.Action("getRutaxCorredor", "Programacion")";
    var URL_IMPORTAR_DATA_DESPACHO = "@Url.Action("importarExcelDespachos", "PicoPlaca")";
    var FECHA_HOY = '@DateTime.Now.ToString("dd/MM/yyyy")';
    var URL_ACTION_UPLOAD_FILE = "@Url.Action("subir_archivo", "PicoPlaca")"
    var URL_GET_REPORTE_BY_FECHAS = "@Url.Action("getReportePicoPlacaByFechas", "PicoPlaca")";
    var URL_ACTION_UPLOAD_FILE_TEST = "@Url.Action("importarExcelDespachosDepura", "PicoPlaca")";
    
</script>

LOGINPUA/Views/PicoPlaca/_RegistroPicoPlaca.cshtml
<div class="modal fade" id="modalRegistroPicoPlaca">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form id="formSubirExcelDespacho" enctype="multipart/form-data">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h6 class="modal-title">Registro</h6>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    
					<div class="form-group">
                         <select class="form-control" name="tipoCarga" id="selectTipocarga" onchange="verificatipoCarga();" >
                            <option value="I">Individual</option>
                            <option value="M">Masivo</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label><strong>Corredor</strong></label>
                        <select class="form-control" id="selectCorredor" onchange="getRutaPorCorredor();"></select>
                    </div>

                    <div class="form-group">
                        <label><strong>Ruta</strong></label>
                        <select class="form-control form-control-sm" id="selectRuta"></select>
                    </div>

                    <div class="form-group" id="sectionFecha">
                        <label><strong>Fecha</strong></label>
                        <input id="txtFechaRegistro" type="text" class="form-control" />
                    </div>

                    <div class="form-group custom-file">
                        <input type="file" name="programacionArchivo" class="custom-file-input" onchange="subirArchivoTemp($(this), $('#selectTipocarga').val())" id="archivoSubido" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
                        <label class="custom-file-label" id="lblArchivoSubido" for="archivoSubido">Seleccionar Archivo</label>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button id="btnSubirArchivo" class="btn btn-info" type="submit">
                        Subir archivo
                    </button>
                    @*<button class="btn btn-info" type="submit" disabled>
                            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                            Subiendo...
                        </button>*@
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>

LOGINPUA/Views/PicoPlaca/_ValidacionPdf.cshtml
@model List<ENTIDADES.CC_RUTA_CORREDOR>
@{
    ViewBag.Title = "Reporte";
    Layout = "~/Views/Shared/_Layout_corredores_Supervisor.cshtml";
}
<link href="~/Content/plugins/sweetAlert/sweetalert2.css" rel="stylesheet" />

<link href="~/Content/plugins/datepicker/bootstrap-datepicker3.min.css" rel="stylesheet" />
<script src="~/Content/js/js_pico_placa/pico_placa.js"></script>
<script src="~/Content/plugins/datepicker/bootstrap-datepicker.min.js"></script>
<script src="~/Scripts/Utilidades/Util.js"></script>
<script src="~/Content/plugins/sweetAlert/sweetalert2.js"></script>

 

    <script>
        window.onload = function () {

            Swal.fire({
                type: 'error',
                title: 'Oops...',
                text: 'Something went wrong!',
             })  
            
        }
        window.close();



    </script>

 