LOGINPUA/Controllers/Usuario_PersonasController.cs
using ENTIDADES;
using LN.EntidadesLN;
using LOGINPUA.Util.Seguridad;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LOGINPUA.Util;
using System.Data;

namespace LOGINPUA.Controllers
{
    public class Usuario_PersonasController : Controller
    {
        //private readonly Usuario_PersonaLN _Usuario_PersonaLN;
        //private readonly Proveedor_ServLN _Proveedor_ServLN;

        //private readonly LoginLN _LoginLN;
        //Util.Util utilidades = new Util.Util();

        //// GET: Usuario_Personas
        //public Usuario_PersonasController()
        //{
        //    _Usuario_PersonaLN = new Usuario_PersonaLN();
        //    _LoginLN = new LoginLN();
        //    _Proveedor_ServLN = new Proveedor_ServLN();
        //}

        public ActionResult MantenimientoUsuario()
        {
            Util.Util utilidades = new Util.Util();
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);
            var Lista_acciones = utilidades.validadAccionMenu(listacciones, nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();
            if (auxValida)
            {
                ViewBag.Accionesview = Lista_acciones;
                return View();
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }
        }

        public string ListarPersonas()
        {
            Usuario_PersonaLN _Usuario_PersonaLN = new Usuario_PersonaLN();
            String mensaje = "";
            Int32 tipo = 0;
            var listaPersona = _Usuario_PersonaLN.ListarPersona(ref mensaje, ref tipo);
            var result = JsonConvert.SerializeObject(listaPersona); //para la lista principal
            return result;
        }

        public string ListarPerfil_modalidad()
        {
            Usuario_PersonaLN _Usuario_PersonaLN = new Usuario_PersonaLN();
            String mensaje = "";
            Int32 tipo = 0;
            var listar = _Usuario_PersonaLN.ListarPerfil_modalidad(ref mensaje, ref tipo);
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }
        public string ListarUsuario_x_ID(int idusuario)
        {
            Usuario_PersonaLN _Usuario_PersonaLN = new Usuario_PersonaLN();
            String mensaje = "";
            Int32 tipo = 0;
            var listar = _Usuario_PersonaLN.ListarUsuario_x_ID(idusuario, ref mensaje, ref tipo);
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }
        public string Consultar_CuentaProvUsu(int id_usuario)
        {
            Usuario_PersonaLN _Usuario_PersonaLN = new Usuario_PersonaLN();
            String mensaje = "";
            Int32 tipo = 0;
            var listar = _Usuario_PersonaLN.Consultar_CuentaProvUsu(id_usuario, ref mensaje, ref tipo);
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }
        public string ListCuentas_x_id(int id_prov_serv)
        {
            Usuario_PersonaLN _Usuario_PersonaLN = new Usuario_PersonaLN();
            String mensaje = "";
            Int32 tipo = 0;
            var listar = _Usuario_PersonaLN.ListCuentas_x_id(id_prov_serv, ref mensaje, ref tipo);
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }

        public string AgregarUsuario(int idpersona, string perfiles, string usuarios, string contraseña, int txtUsuarioProv, string idcorredores, string empresa)
        {
            Proveedor_ServLN _Proveedor_ServLN = new Proveedor_ServLN();
            Usuario_PersonaLN _Usuario_PersonaLN = new Usuario_PersonaLN();
            LoginLN _LoginLN = new LoginLN();
            String mensaje = "";
            Int32 tipo = 0;
            var txtUsuarioProvAbexa = new RPTA_GENERAL();
            var result = "";
            var IdprovABEXA = 0;
            var msj = _LoginLN.Verificar_Usuario(usuarios, contraseña, ref mensaje, ref tipo);

            var listaPersona = _Usuario_PersonaLN.ListarPersona(ref mensaje, ref tipo);
            ViewBag.listaPersona = listaPersona;

            string Session_usuario = Session["user_login"].ToString();
            string[] s_perfiles = new string[10];
            s_perfiles = perfiles.Split('|');

            var msj_final = msj == null ? 0 : msj.ID_USUARIO;
            if (msj_final == 0)
            {
                //ENCRIPTAR CONTRASEÑA
                var contraseña_ = Encriptador.Encriptar(contraseña);

                //REGISTRAR AGREGAR USUARIO
                var rpta = _Usuario_PersonaLN.AgregarUsuario(idpersona, usuarios, contraseña_, Session_usuario, ref mensaje, ref tipo);

                //ID DEL USUARIO CREADO
                var id_usuario = rpta.AUX;

                //AGREGAR PERFILES
                foreach (var id_perfil in s_perfiles)
                {
                    int id_perfil_ = Convert.ToInt32(id_perfil);
                    var rpta_ = _Usuario_PersonaLN.registrarUsuario_Perfil(id_usuario, id_perfil_, Session_usuario, ref mensaje, ref tipo);
                }


                //CREAR (ACTUALIZAR) CUENTA MATRIX
                if (empresa == "MATRIX" || empresa == "MATRIX Y ABEXA")
                {
                 var rpt=_Proveedor_ServLN.Actualizar_Usuario_Prov(txtUsuarioProv, id_usuario, Session_usuario, ref mensaje, ref tipo);
                }
                //CREAR CUENTA ABEXA
                if (empresa == "ABEXA" || empresa == "MATRIX Y ABEXA")
                {
                    txtUsuarioProvAbexa = _Proveedor_ServLN.AgregarUsuario_Proveedor_Usuario(1, id_usuario, usuarios, contraseña_, Session_usuario, ref mensaje, ref tipo);
                    IdprovABEXA = txtUsuarioProvAbexa.AUX;
                }

                if (idcorredores != "")
                {
                    if (empresa == "MATRIX")
                    {
                        //REGISTRAR EL CORREDOR
                        string[] id_corredor_nuevo = idcorredores.Split('|');
                        foreach (var idcorredor in id_corredor_nuevo)
                        {
                            int id_corredores_final = Convert.ToInt32(idcorredor);
                            _Proveedor_ServLN.AgregarUsuario_Corredor(id_corredores_final, txtUsuarioProv, Session_usuario, ref mensaje, ref tipo);
                        }
                    }
                    else if (empresa == "ABEXA")
                    {
                        //REGISTRAR EL CORREDOR
                        string[] id_corredor_nuevo = idcorredores.Split('|');
                        foreach (var idcorredor in id_corredor_nuevo)
                        {
                            int id_corredores_final = Convert.ToInt32(idcorredor);
                            _Proveedor_ServLN.AgregarUsuario_Corredor(id_corredores_final, IdprovABEXA, Session_usuario, ref mensaje, ref tipo);
                        }
                    }
                    else if (empresa == "MATRIX Y ABEXA")
                    {
                        string[] id_corredor_principal = idcorredores.Split(',');

                        //corredor matrix
                        string[] corredor_matrix = id_corredor_principal[0].Split('|');
                        foreach (var idcorredor in corredor_matrix)
                        {
                            int id_corredores_final = Convert.ToInt32(idcorredor);
                            _Proveedor_ServLN.AgregarUsuario_Corredor(id_corredores_final, txtUsuarioProv, Session_usuario, ref mensaje, ref tipo);
                        }
                        //corredor abexa
                        string[] corredor_abexa = id_corredor_principal[1].Split('|');
                        foreach (var idcorredor in corredor_abexa)
                        {
                            int id_corredores_final = Convert.ToInt32(idcorredor);
                            _Proveedor_ServLN.AgregarUsuario_Corredor(id_corredores_final, IdprovABEXA, Session_usuario, ref mensaje, ref tipo);
                        }
                    }
                }

                result = JsonConvert.SerializeObject(rpta);
            }
            else
            {
                RPTA_GENERAL rpt = new RPTA_GENERAL();
                rpt.DES_ESTADO = "Usuario Existente Cambiar";
                rpt.COD_ESTADO = 0;
                result = JsonConvert.SerializeObject(rpt);
            }

            return result;
        }

        public string ListarUsuarios()
        {
            Usuario_PersonaLN _Usuario_PersonaLN = new Usuario_PersonaLN();
            String mensaje = "";
            Int32 tipo = 0;
            var listar = _Usuario_PersonaLN.ListarUsuarios(ref mensaje, ref tipo);

            //Para Saber la clave desencriptada
            List<CC_USUARIO_PERSONA> Lista_Usuario = new List<CC_USUARIO_PERSONA>();
            //foreach (var item in listar)
            //{
            //    CC_USUARIO_PERSONA usuario = new CC_USUARIO_PERSONA();
            //    usuario.ID_USUARIO = item.ID_USUARIO;

            //    var Clave = Encriptador.Desencriptar(item.CLAVE);
            //    usuario.CLAVE = Clave;
            //    usuario.NOMBRE = item.NOMBRE;

LOGINPUA/Views/Usuario_Personas/MantenimientoUsuario.cshtml
@{
    ViewBag.Title = "MantenimientoPerson";
    Layout = "~/Views/Shared/_LayoutInicial.cshtml";
    List<ENTIDADES.CC_PERSONA> lisPersona = new List<ENTIDADES.CC_PERSONA>();
    lisPersona = ViewBag.listaPersona;

    List<ENTIDADES.CC_MENUPERFIL_ACCION> Lista_acciones = ViewBag.Accionesview as List<ENTIDADES.CC_MENUPERFIL_ACCION>;
    int ideliminar = 0;
    int idmodificar = 0;
}

<style>
    .modal-content input {
        width: auto !important;
    }

    .row {
        margin-left: 0px !important;
        margin-right: 0px !important;
    }
</style>
<script src="~/Content/js/js_mantenimiento_usuario/registro_usuario.js@("?v="+ DateTime.Now.ToString("yyyyMMddhmmss"))"></script>
<br />
<div class="row">
    <div class="col-md-12 text-center">
        <h4>
            Registro Usuario&nbsp;&nbsp;&nbsp;

            <button type="button" class="btn btn-info btn-sm" id="btnBusquedaEnTabla">
                <span class="fa fa-search"></span>
            </button>

            @foreach (var item in Lista_acciones)
            {
                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.REGISTRAR.ToString()) //cambiar a enumerado
                {
                    <button type="button" id="modal_registrousu" class="btn btn-success btn-sm" data-toggle="modal" data-target="#exampleModal">
                        <span class="fa fa-plus"></span>
                    </button>
                }

                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.MODIFICAR.ToString())
                {
                    idmodificar = 1;
                    <input type="text" id="permisoActualiza" value="1" hidden />
                }
                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.ANULAR.ToString())
                {
                    ideliminar = 1;
                    <input type="text" id="permisoEliminar" value="1" hidden />
                }
            }


        </h4>
    </div>
</div>

 
<hr />
<div class="row">
    <div class="table-responsive">
        <div>
            <table class="responsive-table" id="tbUsuario" style="width:100%">
                <thead class="thead-azul-claro">
                    <tr>
                        <th style="width: 40px;">N°</th>
                        <th class="text-center">USUARIO</th>
                        <th class="text-center" style="width: 70px;">CONTRASEÑA</th>
                        <th class="text-center" style="width: 195px;">NOMBRES</th>
                        <th class="text-center" style="width: 115px;">APELLIDO PATERNO</th>
                        <th class="text-center" style="width: 115px;">APELLIDO MATERNO</th>
                        <th class="text-center" style="width: 135px;">ESTADO</th>
                        <th class="text-center" style="width: 70px;">USUARIO REGISTRO</th>
                        <th class="text-center" style="width: 140px;">FECHA REGISTRO</th>

                        @if (ideliminar == 1)
                        {
                            <th class="text-center" style="width: 50px;"></th>

                        }
                        @if (idmodificar == 1)
                        {
                            <th class="text-center" style="width: 50px;"></th>

                        }


                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="13" class="text-center">Presionar el boton Consultar para obtener la información.</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@Html.Partial("_RegistroUsuario")
@Html.Partial("_EditarUsuario")

<script>

    var URL_GET_PERFIL_USUARIO = "@Url.Action("ListarPerfil", "Usuario_Personas")";
    var URL_GET_AGREGAR_USUARIOS = "@Url.Action("AgregarUsuario", "Usuario_Personas")";
    var URL_GET_LISTAR_USUARIO = "@Url.Action("ListarUsuarios", "Usuario_Personas")";
    var URL_ANULA_USUARIO = "@Url.Action("Desactivar_Usuarios", "Usuario_Personas")";
    var URL_GET_MODIFICAR_USUARIO = "@Url.Action("ModificarUsuarios", "Usuario_Personas")";
    var URL_GET_PERFIL_MODALIDAD = "@Url.Action("ListarPerfil_modalidad", "Usuario_Personas")";
    var URL_GET_LISTAR_USUARIO_ID = "@Url.Action("ListarUsuario_x_ID", "Usuario_Personas")";
    var URL_GET_LISTAR_PERSONA = "@Url.Action("ListarPersonas", "Usuario_Personas")";
    var URL_GET_PROVVEDOR_SERV = "@Url.Action("ListarProvee_Serv", "Proveedor_Servicio")";
    var URL_GET_LIST_CORREDOR = "@Url.Action("ListCorredores", "Proveedor_Servicio")";
    var URL_GET_LIST_CUENTAS_X_ID= "@Url.Action("ListCuentas_x_id", "Usuario_Personas")";
    var URL_GET_CONSULTAR_CUENTAPROVUSU= "@Url.Action("Consultar_CuentaProvUsu", "Usuario_Personas")";

    

</script>

LOGINPUA/Views/Usuario_Personas/_EditarUsuario.cshtml
<style>
    .ms-options {
        min-height: 0;
    }


    legend.scheduler-border {
        width: inherit; /* Or auto */
        padding: 0 10px; /* To give a bit of padding on the left and right */
        border-bottom: none;
    }
</style>

<div class="modal fade" id="EditarModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h6 class="modal-title" id="tituloDialog">Editar Usuario</h6>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>

            <div class="form-group container">

                <fieldset class="border p-1">
                    <legend class="scheduler-border" style="font-size:18px">USUARIO</legend>
                    <div class="control-group">
                        <div class="form-group row">


                            <h3 class="col-sm-2 col-form-label">Contraseña</h3>
                            <div class="col-sm-3">
                                <input type="password" class="form-control" placeholder="Nueva Contraseña" style="width:118%" id="clave_edit" name="name" value="" />
                            </div>
                            <div class="col-sm-1"></div>
                            <h3 class="col-sm-2 col-form-label">Estado</h3>
                            <div class="col-sm-3">
                                <select id="idestado_edit" class="form-control" style="width:120%">
                                    <option value="1">ACTIVO</option>
                                    <option value="2">DESACTIVADO</option>
                                </select>
                            </div>

                        </div>

                    </div>


                </fieldset>

                <br />

                <fieldset class="border p-1">
                    <legend class="scheduler-border" style="font-size:18px">PERFIL POR MODALIDAD</legend>
                    <br />
                    <div class="control-group">
                        <div class="" id="txtmodalidad_perfil">


                        </div>
                    </div>

                </fieldset>

                <div id="fieldset_buton_edit">
                     <fieldset class="border p-1">
                        <legend class="scheduler-border" style="font-size:18px">PROVEEDOR CUENTA</legend>

                        <div id="div_abexa_edit">
                            <div class="control-group">
                                <div class="form-group row">
                                    <h3 class="col-sm-2 col-form-label">Proveedor</h3>
                                    <div class="col-sm-3">
                                        <select id="txtAbexaSelect_EDIT" style="width:137%" class="form-control" data-live-search="true">
                                            <option value="1">ABEXA</option>
                                        </select>
                                    </div><div class="col-sm-1"></div>

                                    <h3 class="col-sm-2 col-form-label">Corredores</h3>
                                    <div class="col-sm-3" id="div_context_ABEXA"> 
                                        </div>
                                </div>

                                <div class="form-group row">
                                    <h3 class="col-sm-2 col-form-label">Usuario</h3>
                                    <div class="col-sm-3">
                                        <input type="text" disabled class="form-control" id="txtabexa_usuario_edit" name="name" value="" />
                                    </div><div class="col-sm-1"></div>

                                    <h3 class="col-sm-2 col-form-label">Contraseña</h3>
                                    <div class="col-sm-3"><input id="txtabexa_contraseña_edit" disabled type="text" class="form-control" name="name" value="" /></div>
                                </div>
                            </div>

                        </div>


                        <div id="div_matrix_edit" >
                            <div class="control-group">
                                <div class="form-group row">
                                    <h3 class="col-sm-2 col-form-label">Proveedor</h3>  
                                    <div class="col-sm-3">
                                        <select id="txtMatrixSelect_EDIT" style="width:137%" class="form-control" data-live-search="true">
                                            <option value="2">MATRIX</option>
                                        </select>
                                    </div><div class="col-sm-1"></div>

                                    <h3 class="col-sm-2 col-form-label">Usuario</h3>
                                    <div class="col-sm-3">
                                        <input id="txtUsuarioProvMATRIX_EDIT" class="form-control" data-live-search="true" disabled>

                                    </div>
                                </div>
                            </div>


                            <div class="control-group">
                                <div class="form-group row">
                                         <h3 class="col-sm-2 col-form-label">Corredores</h3>
                                        <div class="col-sm-3" id="div_context_MATRIX">
                                        </div><div class="col-sm-1"></div>
 
                                    <h3 class="col-sm-2 col-form-label">Contraseña</h3>
                                    <div class="col-sm-3">
                                        <input type="text" disabled class="form-control" id="txtcontraseña_MATRIX_edit" name="name" value="" />
                                    </div>
                                </div>
                            </div>
                        </div>

                    </fieldset>
                </div>




                <div class="modal-footer">
                    <button id="consultar" onclick="Update_Usuario()" class="btn btn-info" type="button">
                        Guardar
                    </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
</div>

LOGINPUA/Views/Usuario_Personas/_RegistroUsuario.cshtml
<style>
    .ms-options {
        min-height: 0;
    }


    legend.scheduler-border {
        width: inherit; /* Or auto */
        padding: 0 10px; /* To give a bit of padding on the left and right */
        border-bottom: none;
    }
</style>

<div class="modal fade" id="exampleModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h6 class="modal-title" id="tituloDialog">Registrar Nuevo Usuario</h6>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>





            <div class="form-group container">

                <fieldset class="border p-1">
                    <legend class="scheduler-border" style="font-size:18px">USUARIO</legend>
                    <div class="control-group">
                        <div class="form-group row">
                            <h3 class="col-sm-2 col-form-label">Personas</h3>
                            <div class="col-sm-3">
                                <select id="idpersona" class="selectpicker" data-live-search="true"></select>
                            </div><div class="col-sm-1"></div>

                            <h3 class="col-sm-2 col-form-label">Usuario</h3>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" style="width:118%" id="usuario" name="name" value="" disabled>
                            </div>
                        </div>
                    </div>



                    <div class="form-group row">
                        <h3 class="col-sm-2 col-form-label">Contraseña</h3>
                        <div class="col-sm-3">
                            <input type="password" class="form-control" style="width:118%" id="clave1" name="name" value="" />
                        </div><div class="col-sm-1"></div>

                        <h3 class="col-sm-2 col-form-label">Confirmar Contraseña</h3>
                        <div class="col-sm-3">
                            <input type="password" class="form-control" style="width:118%" id="clave2" name="name" value="" />
                        </div>
                    </div>


                    <select id="idestado" class="form-control" style="width:118%" hidden>
                        <option value="1">Activado</option>
                        <option value="2">Desactivado</option>
                    </select>

                </fieldset>

                <br />

                <fieldset class="border p-1">
                    <legend class="scheduler-border" style="font-size:18px">PERFIL POR MODALIDAD</legend>
                    <br />
                    <div class="control-group">
                        <div class="form-group row" id="txtperfil">
                        </div>
                    </div>
                </fieldset>
                <br />

                <button id="button_cambio" style="margin-left: 718px;margin-top: -27px;" class="btn btn-info btn-sm"><i class="fas fa-user-cog"></i></button>     
                <div id="fieldset_buton" style="display: none;">
                    <div class="form-group row">
                        <div class="col-md-2"></div>

                        <div class="col-md-5">
                            <div class="custom-control custom-radio">
                                <input type="checkbox" id="AbexaRadio1" name="customRadio" class="custom-control-input" value="AbexaRadio1" >
                                <label class="custom-control-label" for="AbexaRadio1">ABEXA</label>
                            </div>
                        </div>

                        <div class="col-md-5">
                            <div class="custom-control custom-radio">
                                <input type="checkbox" id="MatrixRadio2" name="customRadio" class="custom-control-input" value="MatrixRadio2" >
                                <label class="custom-control-label" for="MatrixRadio2">MATRIX</label>
                            </div>
                        </div>


                    </div>

                    <fieldset class="border p-1"  >
                        <legend class="scheduler-border" style="font-size:18px">PROVEEDOR CUENTA</legend>

                        <div id="div_abexa" style="display:none">
                            <div class="control-group">
                                <div class="form-group row">
                                    <h3 class="col-sm-2 col-form-label">Proveedor</h3>
                                    <div class="col-sm-3">
                                        <select id="txtAbexaSelect" style="width:137%" class="form-control" data-live-search="true">
                                            <option value="1">ABEXA</option>
                                        </select>
                                    </div><div class="col-sm-1"></div>

                                    <h3 class="col-sm-2 col-form-label">Corredores</h3>
                                    <div class="col-sm-3">
                                        <div id="idcorredores_div">
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>


                        <div id="div_matrix" style="display:none">
                            <div class="control-group">
                                <div class="form-group row">
                                    <h3 class="col-sm-2 col-form-label">Proveedor</h3>
                                    <div class="col-sm-3">
                                        <select id="txtPROVEEDORSERV" style="width:137%" class="form-control" data-live-search="true"></select>
                                    </div><div class="col-sm-1"></div>

                                    <h3 class="col-sm-2 col-form-label">Usuario</h3>
                                    <div class="col-sm-3">
                                        <select id="txtUsuarioProv" class="selectpicker" data-live-search="true"></select>

                                    </div>
                                </div>
                            </div>


                            <div class="control-group">
                                <div class="form-group row">
                                    <h3 class="col-sm-2 col-form-label">Corredores</h3>
                                    <div class="col-sm-3">
                                        <div id="div_context_Matrix">
                                            <select multiple id="id_corredor_MATRIX">
                                                <option value="5">PN</option>
                                                <option value="2">JP</option>
                                            </select>

                                        </div>

                                     </div><div class="col-sm-1"></div>

                                    <h3 class="col-sm-2 col-form-label">Contraseña</h3>
                                    <div class="col-sm-3">
                                        <input type="text" disabled class="form-control" id="txtcontraseña_prov" name="name" value="" />
                                    </div>
                                </div>
                            </div>
                        </div>

                    </fieldset>
                </div>




                <div class="modal-footer">
                     <button id="consultar" onclick="AgregarUsuarios()" class="btn btn-info" type="button">
                        Guardar
                    </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
</div>
 
 